### ISSUE TITLE
Create a getting started guide

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#26]
- [x] Create first draft
- [x] Review and enrich
- [x] Publish

**Comment by marty-2015** [comment]
Path: docs/src/guides/

**Comment by SteinRobert** [comment]
The unikube.yaml file - yes. The shell commands are still too indented.

**Comment by marty-2015** [comment]
I don't see any other indented lines in this doc: https://docs.google.com/document/d/1i6cIpgz4bCtDKwh8qJDsK-ykjv4mGD3A48IHwdIp82c/edit#

**Comment by SteinRobert** [comment]
>I don't see any other indented lines in this doc: https://docs.google.com/document/d/1i6cIpgz4bCtDKwh8qJDsK-ykjv4mGD3A48IHwdIp82c/edit#

Exactly. That's why I was wondering the commands the documentation have too much indentation. 

Please compare https://unikube.io/docs/guides/installation.html#installation-via-pip with yours https://unikube.io/docs/guides/getting-started.html#local-machine-setup

The commands in the "getting started guide" have too much indentation.
